name: Compile and Deploy ssgo to server

on:
    push:
        tags:
            - 'v*'

jobs:
    deploy:
        runs-on:
            ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Connect to Tailscale VPN
                uses: tailscale/github-action@v4
                with:  
                    authkey: ${{ secrets.TAILSCALE_KEY }}
            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.22'

            -   name: Set up Bun
                uses: oven-sh/setup-bun@v2
                with:
                    bun-version: latest

            -   name: Build Vite Frontend
                run: |
                    cd web
                    bun install
                    bun run build

            -   name: Run Unit Tests
                run : go test -v ./...

            -   name: Compile Linux Binary
                run: |
                    GOOS=linux GOARCH=amd64 go build -o ssgo ./cmd/ssgo

            -   name: Copy Binary to Server via ssh
                uses: appleboy/scp-action@v0.1.7
                with: 
                    host: ${{ secrets.SERVER_HOST}}
                    username: ${{ secrets.SERVER_USER}}
                    key: ${{secrets.SSH_PRIVATE_KEY}}
                    source: "ssgo"
                    target: "/tmp/"
            -   name: Install Binary to /usr/local/bin on Server
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        mkdir -p ~/.local/bin
                        mv /tmp/ssgo ~/.local/bin/ssgo
                        chmod +x ~/.local/bin/ssgo
                        sudo systemctl restart ssgo || true
                        echo "Successfully updated and restarted ssgo!"